quarkus.application.name=sislogica-api
quarkus.application.version=1.0.0-SNAPSHOT

# HTTP Configuration
quarkus.http.port=8080

# Database Configuration (PostgreSQL)
quarkus.datasource.db-kind=postgresql

# Em desenvolvimento, conecta no PostgreSQL do docker-compose local
%dev.quarkus.datasource.username=sislogica_user
%dev.quarkus.datasource.password=sislogica_password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sislogica_db

# Em producao, consome variaveis de ambiente
%prod.quarkus.datasource.username=${DB_USER:sislogica_user}
%prod.quarkus.datasource.password=${DB_PASSWORD:sislogica_password}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/sislogica_db}

# Em testes, o Quarkus Dev Services (Testcontainers) gerencia o banco PostgreSQL automaticamente
# Sem URL fixa, garantindo execucao no Docker Desktop e no GitHub Actions CI!
%test.quarkus.datasource.devservices.enabled=true

# Hibernate ORM (O esquema deve ser gerado EXCLUSIVAMENTE por migracoes Flyway)
quarkus.hibernate-orm.database.generation=none

# Flyway Migrations
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# OpenAPI & Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui
